/**
 * Landing kopya sözlüğü — TR + EN. Tüm landing bölümleri (statik + client
 * bileşenler) buradan beslenir. messages/{tr,en}.ts'ten ayrı tutuldu (oradaki
 * Messages tipi paritesi eski sayfa yapısına bağlı; landing kopyası bağımsız).
 */
export type LandingLocale = 'tr' | 'en';

export const landingCopy = {
  tr: {
    nav: {
      links: [
        { href: '#ozellikler', label: 'Özellikler' },
        { href: '#cekilis', label: 'Çekiliş' },
        { href: '#shopper', label: 'Mobil' },
        { href: '#fiyat', label: 'Fiyat' },
        { href: '#sss', label: 'SSS' },
      ],
      lang: 'EN',
      langHref: '/en/',
      download: 'İndir',
    },
    hero: {
      live: 'CANLI SATIŞ İÇİN',
      platform: 'Windows 10 / 11',
      title: ['Sohbet akar.', 'Etiket basılır.', 'Çark döner.'],
      titleEm: 'basılır.',
      sub: 'Instagram, TikTok, Facebook ve YouTube canlı sohbetleri tek pencerede. Müşteri “aldım” yazdığı an sipariş etikete döner, çekiliş OBS yayınında canlı döner — sen yayını hiç bölmezsin.',
      ctaPrimary: '14 gün ücretsiz dene',
      ctaGhost: 'Nasıl çalışır',
      micro: ['Kart bilgisi istemez', 'Kurulum 2 dakika', 'Veriler senin makinende'],
    },
    studio: {
      file: 'OrderDeck — yayın #318',
      live: 'CANLI',
      chatHead: 'BİRLEŞİK SOHBET',
      chatRate: (n: number) => `4 platform · ${n}/dk`,
      filter: 'spam: link içeren 2 mesaj filtrelendi',
      labelHead: 'SİPARİŞ → ETİKET',
      lfUser: 'MÜŞTERİ',
      lfMsg: 'MESAJ',
      lfBtn: 'Yazdır',
      wheelHead: 'ÇEKİLİŞ',
      parts: 'katılımcı',
      tkAmount: 'TUTAR',
      tkFoot: 'YAYIN #318',
      pauseOn: 'Animasyonu duraklat',
      pauseOff: 'Animasyonu sürdür',
    },
    ticker: ['INSTAGRAM','TIKTOK','FACEBOOK','YOUTUBE','ANLIK ETİKET','DEKONT DOĞRULAMA','ÇARK ÇEKİLİŞİ','YEDEK SATIŞ','WHATSAPP ÖDEME','PUSH BİLDİRİM','YAYIN RAPORU','OBS OVERLAY'],
    stats: [
      { b: '4', s: 'platform, tek pencere' },
      { b: 'Tek tık', s: 'mesajdan termal etikete' },
      { b: '≈%90+', s: 'sahte dekont elenir' },
      { b: '0', s: 'veri sunucuya gider' },
    ],
    sec01: {
      kicker: '01 · YAYIN & SOHBET',
      h2: 'Dört platformu aynı anda dinle, gürültüyü sen duyma',
      p: 'Pencere değiştirmek yok. Bütün sohbet kronolojik tek akışta; trol ve spam sana ulaşmadan elenir.',
      card1H: '4 platform tek panelde',
      card1P: 'Instagram, TikTok, Facebook ve YouTube canlı sohbetleri aynı anda, kronolojik tek listede akar. Ek hesap ya da API anahtarı oluşturman gerekmez — bağlan, yayına başla.',
      card1Arrow: '→ tek liste',
      card2Strike: 'bit.ly/kazan…',
      card2Elim: '→ elendi',
      card2H: 'Spam & trol filtresi',
      card2P: 'Linkler, tekrar eden mesajlar, hep-büyük-harf yazımlar ve senin belirlediğin yasaklı kelimeler sohbete hiç düşmez. Listeyi sen yönetirsin.',
    },
    sec02: {
      kicker: '02 · SİPARİŞ & ETİKET',
      h2a: '“Aldım” yazıldığı an, etiket ',
      h2em: 'yazıcıdan',
      h2b: ' çıkar',
      p: 'OrderDeck’in kalbi burası. Mesajı seç, fiyatı gir, Enter. Termal yazıcı gerisini halleder — yayın hiç durmaz.',
      ticks: [
        ['Tek tıkla iptal', ' — yanlış etiket mi bastın? Neden seçenekleriyle anında geri al.'],
        ['Yedek (standby) satış', ' — müşteri vazgeçerse sipariş otomatik yedek alıcıya devreder.'],
        ['Kümülatif kargo eşiği', ' — toplam eşik altındaysa kargo satırı etikete kendiliğinden eklenir.'],
        ['WhatsApp ile ödeme isteği', ' — IBAN/ödeme mesajı müşteriye tek tıkla gider.'],
        ['Yayın raporu & geçmişi', ' — ciro, özet ve geçmiş yayınlar; tek tıkla Excel’e.'],
      ],
      note: 'Argox, Zebra, TSC ve Windows’ta tanımlı tüm termal etiket yazıcılarıyla çalışır.',
    },
    printer: {
      head: 'termal yazıcı · hazır',
      idle: 'BEKLİYOR',
      printed: 'BASILDI',
      btn: 'Etiketi bas',
      foot: 'OrderDeck ile basıldı',
      amount: 'TUTAR',
      yayin: 'YAYIN #318',
      standby: 'YEDEK ALICI',
      cargo: 'kargo (eşik altı)',
    },
    sec03: {
      kicker: '03 · GÜVENLİ TAHSİLAT',
      h2a: 'Sahte dekont gönderen ',
      h2em: 'kapıdan giremez',
      h2b: '',
      p: 'Müşteriden gelen banka dekontunu (WhatsApp/e-posta PDF) ekle; OrderDeck dekontu doğru müşteri ve siparişle otomatik eşleştirir, tutar ve gönderen uyuşmazlıklarını anında yakalar.',
      ticks: [
        ['Otomatik eşleştirme', ' — dekont, doğru müşteri ve siparişle kendiliğinden bağlanır.'],
        ['Uyuşmazlık alarmı', ' — tutar ya da gönderen tutmuyorsa işaretlenir, gözden kaçmaz.'],
        ['“Ödedim” yalanına son', ' — ödemeden sipariş kapatan ya da sahte fiş atan dolandırıcılığı keser.'],
      ],
      shieldLbl: 'düzmece / sahte dekont otomatik elenir',
      okName: '@ayse34 · ₺250',
      okDesc: 'dekont eşleşti · sipariş onaylandı',
      badName: '@kullanici_x · ₺250',
      badDesc: 'sahte dekont — tutar / gönderen uyuşmuyor',
    },
    giveaway: {
      kicker: '04 · ÇEKİLİŞ',
      h2: 'Çekiliş, izleyicinin gözü önünde döner',
      p: 'Anahtar kelimeyi söyle; yazan herkes otomatik listeye girer. Çark OBS yayın katmanında döner, kazananı binlerce kişi aynı anda görür. İtiraz yok, ekran görüntüsü isteyen yok.',
      pills: ['10+ çark & animasyon', 'mükerrer katılım engeli'],
      noteB: 'Kazanan etiketi otomatik basılır.',
      note: ' Çekiliş biter bitmez kazananın etiketi yazıcıdan çıkar — ödülü kim aldı, kayıt altında.',
      btn: 'Çarkı çevir',
      obsTag: 'OBS YAYIN KATMANI · CANLI',
      spin: 'ÇEVİR',
      waiting: 'kazanan bekleniyor…',
      spinning: 'çark dönüyor…',
      winnerPre: '🏆 kazanan: ',
      winnerPost: ' · etiketi basıldı',
    },
    shopper: {
      kicker: '05 · MÜŞTERİ & MOBİL',
      h2: 'Müşterini tanı, bakiyesini tut, uygulamasını ver',
      p: 'Yayında biriken her müşteri için bir kart: cari/bakiye, iade ve geçmiş tek yerde. Sorunlu kullanıcıları kara listeye al; gerisini Shopper halleder.',
      feats: [
        ['Cari & bakiye', 'Müşteri kartı, bakiye, iade ve sipariş geçmişi.'],
        ['Kara liste', 'Sorunlu kullanıcıları işaretle, otomatik uzak tut.'],
        ['Shopper uygulaması', 'Müşteri kayıt olur, siparişlerini ve bakiyesini görür, parolasını kendi sıfırlar.'],
        ['Anında push bildirim', 'Yeni yayın, duyuru ve ödeme olaylarında müşteriye Shopper’dan anında bildirim.'],
        ['Duyuru & akış', 'Metin + fotoğraf paylaş; müşteriler Shopper akışında görür, push alır.'],
        ['Özel kayıt formu', 'Yayına özel, özelleştirilebilir formla müşteri topla.'],
      ],
      push: ['🔔 OrderDeck · ', 'Yayın başladı!', ' Bu akşam 21:00'],
      orders: 'Siparişlerim',
      order1: ['Mor triko · 38', 'Yayın #318 · ₺250', 'Ödendi'],
      order2: ['Şal · krem', 'Yayın #318 · ₺120', 'Bekliyor'],
      order3: ['Kargo', 'Eşik altı · ₺60', 'Bekliyor'],
      balLabel: 'Güncel bakiye',
      balPending: 'Bekleyen ödeme',
      balMonth: 'Bu ay sipariş',
      payBtn: 'WhatsApp’tan öde',
      pwHint: 'Parolanı uygulamadan kendin sıfırlayabilirsin.',
    },
    trust: [
      ['Yerel ve gizli', 'Sohbet verileri senin makinende kalır. OrderDeck sunucularına gönderilmez; uygulama kapanınca silinir.', null],
      ['Yedekleme & geri yükleme', 'Veriyi yedekle, geri yükle, lisansı başka makineye taşı. Arıza senin işini durdurmaz.', null],
      ['Otomatik güncelleme', 'Yeni sürümler uygulama içinden gelir. Sen sadece yayına bak.', null],
      ['Toplu SMS kampanyaları', 'Müşteri listene toplu kampanya. ', 'Çok yakında.'],
    ],
    pricing: {
      kicker: 'FİYATLANDIRMA',
      h2: 'Bir kez öde, ömür boyu senin',
      p: 'Abonelik yok. Aldığın sürüm senindir; ilk yıl güncellemeler dahil, sonrası tamamen opsiyonel.',
      badge: 'ÖMÜR BOYU LİSANS',
      price: '250.000\u00a0₺',
      priceNote: 'tek seferlik',
      feats: ['4 platform birden','Anlık etiket basımı','Yedek satış + kargo eşiği','WhatsApp ödeme isteği','Banka dekontu doğrulama','Çekiliş + OBS overlay','Kazanan etiketi otomatik','Müşteri / cari / bakiye','Shopper + push bildirim','Duyuru & özel kayıt formu','Yayın raporu + geçmiş → Excel','Spam & trol filtresi','Yedekleme & geri yükleme','İlk yıl güncelleme dahil'],
      cta: 'Lisans al',
      ctaNote: 'Tek kişiye/işletmeye özel · WhatsApp ile aktivasyon',
      addonKicker: 'SONRAKİ YILLAR — OPSİYONEL',
      addonTitle: 'Güncelleme + destek',
      addonPrice: '10.000\u00a0₺',
      addonPer: '/yıl',
      addonP: 'Yeni özellikler, platform değişiklikleri için API tamirleri, öncelikli e-posta desteği (24 saat içinde yanıt). İlk yıl ücretsiz dahildir; almazsan mevcut sürüm çalışmaya devam eder.',
      ctxKicker: 'NEYİ ORTADAN KALDIRIR',
      ctxP: 'İkinci telefonu, açık unutulan sekmeleri, kayıp siparişi ve “kim ne aldı” kavgasını. Tek pencere, tek akış, temiz kayıt.',
      trial: '14 gün ücretsiz tam deneme · kart bilgisi istemez',
    },
    faqTitle: { kicker: 'SIKÇA SORULANLAR', h2: 'Merak edilenler' },
    faq: [
      ['OrderDeck nedir?', 'Instagram, TikTok, Facebook ve YouTube canlı yayın sohbetlerini birleştiren, sipariş alıp etiket basan, çekiliş ve müşteri yöneten bir Windows masaüstü uygulaması. Mezat usulü canlı satış yapan yayıncılar için tasarlandı.'],
      ['Hangi yazıcılar destekleniyor?', 'Windows üzerinde tanımlı her termal etiket yazıcısı çalışır. Geliştirme sırasında Argox, Zebra ve TSC modelleriyle test edildi.'],
      ['Yayın platformları için ek hesap/API anahtarı gerekiyor mu?', 'Hayır. Ayrı bir API anahtarı oluşturman ya da geliştirici hesabı açman gerekmez; bağlanmak istediğin platform hesaplarınla giriş yapıp yayına başlarsın.'],
      ['Mesajlar bir yerde saklanıyor mu?', 'Hayır. Tüm mesajlar yalnızca senin makinende, son 500 mesaja kadar bellekte tutulur ve uygulama kapanınca silinir. OrderDeck sunucularına gönderilmez.'],
      ['Deneme süresi nasıl çalışıyor?', 'İlk kurulumda 14 gün ücretsiz tam deneme aktiftir. Süre dolunca lisans almazsan uygulama salt-okunur moda geçer; eski etiketlerin korunur ama yeni yayın açamazsın.'],
      ['Lisans birden fazla makinede çalışır mı?', 'Tek lisans tek makineye bağlıdır. Yedek bilgisayar için makineler arası transferi panelden, destek talebi açmadan yapabilirsin (ayda 2 kez).'],
      ['Neden abonelik değil de ömür boyu lisans?', 'OrderDeck dış platformlara bağlı olduğundan, platformlar değiştikçe sürekli bakım yapıyoruz. Sen bir kez ödeyip sahip olursun; biz de opsiyonel güncelleme paketiyle bakımı sürdürürüz. Bu model ikimiz için de adil.'],
    ] as [string, string][],
    download: {
      kicker: 'İNDİR',
      h2: 'OrderDeck’i bu akşam kur',
      p: 'Windows 10 (22H2+) ve 11 için self-contained kurulum — ek .NET ya da başka runtime kurmana gerek yok.',
      version: 'SÜRÜM',
      size: 'BOYUT',
      date: 'YAYIN TARİHİ',
      btn: 'Şimdi indir',
      sub: '14 gün tam deneme · kart bilgisi istemez',
      warnH: 'SmartScreen uyarısı çıkarsa',
      warnP: 'OrderDeck şimdilik kod imzalama sertifikasız dağıtılıyor (2026 Q3’te eklenecek). Windows “PC’nizi korudu” uyarısı gösterirse:',
      warnSteps: ['“Daha fazla bilgi” linkine tıkla', '“Yine de çalıştır” butonuna bas'],
      afterH: 'Kurulumdan sonra',
      afterSteps: ['İlk açılışta kurulum sihirbazı otomatik başlar.', '6 adımda lisans aktivasyonu, YouTube kanal ayarı, Chrome eklentisi ve OBS browser source URL’leri ayarlanır.', 'Chrome eklentisi mağaza onayı beklerken sihirbaz sideload adımlarını gösterir.'],
      reqH: 'Sistem gereksinimleri',
      req: ['Windows 10 (22H2+) veya Windows 11', '64-bit işlemci (Intel/AMD veya ARM64)', '~500 MB boş disk alanı', 'Lisans aktivasyonu için internet bağlantısı', 'Google Chrome (canlı yayın chat’i için)'],
    },
    footer: {
      tagline: 'Türk mezat yayıncıları için tek pencerede sohbet, etiket ve çekiliş.',
      contact: 'Musa Sevinç · support@orderdeckapp.com',
      colProduct: 'Ürün',
      product: [['#ozellikler','Özellikler'],['#fiyat','Fiyatlandırma'],['#sss','SSS'],['/blog/','Blog']],
      colLegal: 'Yasal',
      legal: [['/gizlilik-politikasi/','Gizlilik Politikası'],['/kullanim-kosullari/','Kullanım Koşulları'],['/iletisim/','İletişim']],
      rights: '© 2026 Musa Sevinç. Tüm hakları saklıdır.',
    },
    chatPool: [
      { p: 'ig', u: 'ayse34', m: 'aldım 250', buy: true, price: 250, item: 'kırmızı 38' },
      { p: 'tt', u: 'mehmet_k', m: 'XL var mı?' },
      { p: 'fb', u: 'fatma.gul', m: 'aldım kırmızı 38', buy: true, price: 180, item: 'kırmızı 38' },
      { p: 'yt', u: 'ali_eks', m: 'bana da ayır' },
      { p: 'ig', u: 'zey.no', m: 'çekilişe yazıldım' },
      { p: 'tt', u: 'derya.b', m: 'fiyat ne kadar' },
      { p: 'ig', u: 'selin_24', m: 'aldım 320', buy: true, price: 320, item: 'mor triko' },
      { p: 'fb', u: 'hatice.k', m: 'kargo dahil mi' },
      { p: 'yt', u: 'burak.t', m: 'aldım 150', buy: true, price: 150, item: 'şal krem' },
      { p: 'tt', u: 'esra_m', m: 'beden tablosu?' },
      { p: 'ig', u: 'gul.han', m: 'aldım 410', buy: true, price: 410, item: 'kaban L' },
      { p: 'fb', u: 'yusuf99', m: 'stok kaldı mı' },
    ],
    printerSamples: [
      { plat: 'IG', user: 'ayse34', item: 'kırmızı triko · 38', price: 250, cargo: false, standby: false },
      { plat: 'TT', user: 'mehmet_k', item: 'kaban · L', price: 410, cargo: true, standby: false },
      { plat: 'FB', user: 'selin_24', item: 'mor elbise · M', price: 180, cargo: false, standby: true },
      { plat: 'YT', user: 'gul.han', item: 'şal · krem', price: 120, cargo: true, standby: false },
    ],
  },

  en: {
    nav: {
      links: [
        { href: '#ozellikler', label: 'Features' },
        { href: '#cekilis', label: 'Giveaways' },
        { href: '#shopper', label: 'Mobile' },
        { href: '#fiyat', label: 'Pricing' },
        { href: '#sss', label: 'FAQ' },
      ],
      lang: 'TR',
      langHref: '/',
      download: 'Download',
    },
    hero: {
      live: 'BUILT FOR LIVE SELLING',
      platform: 'Windows 10 / 11',
      title: ['Chat flows in.', 'Labels print out.', 'The wheel spins.'],
      titleEm: 'print out.',
      sub: 'Instagram, TikTok, Facebook and YouTube live chat in one window. The moment a buyer types “sold”, the order becomes a label; the giveaway wheel spins live on your OBS stream — you never break the broadcast.',
      ctaPrimary: 'Start 14-day free trial',
      ctaGhost: 'How it works',
      micro: ['No card required', '2-minute setup', 'Your data stays on your machine'],
    },
    studio: {
      file: 'OrderDeck — stream #318',
      live: 'LIVE',
      chatHead: 'UNIFIED CHAT',
      chatRate: (n: number) => `4 platforms · ${n}/min`,
      filter: 'spam: 2 messages with links filtered out',
      labelHead: 'ORDER → LABEL',
      lfUser: 'CUSTOMER',
      lfMsg: 'MESSAGE',
      lfBtn: 'Print',
      wheelHead: 'GIVEAWAY',
      parts: 'entrants',
      tkAmount: 'TOTAL',
      tkFoot: 'STREAM #318',
      pauseOn: 'Pause animation',
      pauseOff: 'Resume animation',
    },
    ticker: ['INSTAGRAM','TIKTOK','FACEBOOK','YOUTUBE','INSTANT LABEL','RECEIPT VERIFICATION','WHEEL GIVEAWAY','BACKUP SALE','WHATSAPP PAYMENT','PUSH NOTIFICATION','STREAM REPORT','OBS OVERLAY'],
    stats: [
      { b: '4', s: 'platforms, one window' },
      { b: 'One click', s: 'from message to label' },
      { b: '≈90%+', s: 'fake receipts caught' },
      { b: '0', s: 'data sent to servers' },
    ],
    sec01: {
      kicker: '01 · STREAM & CHAT',
      h2: 'Listen to four platforms at once, skip the noise',
      p: 'No window switching. All chat in one chronological feed; trolls and spam are filtered before they reach you.',
      card1H: '4 platforms in one panel',
      card1P: 'Instagram, TikTok, Facebook and YouTube live chat flow into one chronological list at the same time. No extra accounts or API keys to create — connect and go live.',
      card1Arrow: '→ one list',
      card2Strike: 'bit.ly/win…',
      card2Elim: '→ filtered',
      card2H: 'Spam & troll filter',
      card2P: 'Links, repeated messages, ALL-CAPS shouting and the banned words you define never reach the chat. You manage the list.',
    },
    sec02: {
      kicker: '02 · ORDER & LABEL',
      h2a: 'The instant “sold” is typed, the label ',
      h2em: 'leaves the printer',
      h2b: '',
      p: 'This is the heart of OrderDeck. Pick the message, enter the price, hit Enter. The thermal printer handles the rest — the broadcast never stops.',
      ticks: [
        ['One-click cancel', ' — printed the wrong label? Undo instantly, with reason options.'],
        ['Backup (standby) sale', ' — if a buyer backs out, the order moves to a backup buyer automatically.'],
        ['Cumulative shipping threshold', ' — if the total is below the threshold, a shipping line is added to the label automatically.'],
        ['WhatsApp payment request', ' — the IBAN/payment message goes to the customer in one click.'],
        ['Stream report & history', ' — revenue, summary and past streams; export to Excel in one click.'],
      ],
      note: 'Works with Argox, Zebra, TSC and every thermal label printer installed on Windows.',
    },
    printer: {
      head: 'thermal printer · ready',
      idle: 'IDLE',
      printed: 'PRINTED',
      btn: 'Print label',
      foot: 'Printed with OrderDeck',
      amount: 'TOTAL',
      yayin: 'STREAM #318',
      standby: 'BACKUP BUYER',
      cargo: 'shipping (below threshold)',
    },
    sec03: {
      kicker: '03 · SECURE COLLECTION',
      h2a: 'Anyone sending a fake receipt ',
      h2em: 'gets stopped at the door',
      h2b: '',
      p: 'Add the bank receipt from the customer (WhatsApp/e-mail PDF); OrderDeck matches it to the right customer and order automatically, and catches amount or sender mismatches instantly.',
      ticks: [
        ['Automatic matching', ' — the receipt links itself to the right customer and order.'],
        ['Mismatch alert', ' — if the amount or sender doesn’t match, it’s flagged so nothing slips through.'],
        ['End of the “I paid” lie', ' — stops fraudsters who close orders without paying or send fake receipts.'],
      ],
      shieldLbl: 'bogus / fake receipts filtered automatically',
      okName: '@ayse34 · ₺250',
      okDesc: 'receipt matched · order confirmed',
      badName: '@user_x · ₺250',
      badDesc: 'fake receipt — amount / sender mismatch',
    },
    giveaway: {
      kicker: '04 · GIVEAWAY',
      h2: 'The giveaway spins before your viewers’ eyes',
      p: 'Announce a keyword; everyone who types it joins automatically. The wheel spins on your OBS stream layer, and thousands see the winner at the same moment. No disputes, no screenshot requests.',
      pills: ['10+ wheels & animations', 'duplicate-entry block'],
      noteB: 'The winner’s label prints automatically.',
      note: ' The moment the giveaway ends, the winner’s label leaves the printer — who got the prize is on record.',
      btn: 'Spin the wheel',
      obsTag: 'OBS STREAM LAYER · LIVE',
      spin: 'SPIN',
      waiting: 'waiting for winner…',
      spinning: 'wheel spinning…',
      winnerPre: '🏆 winner: ',
      winnerPost: ' · label printed',
    },
    shopper: {
      kicker: '05 · CUSTOMER & MOBILE',
      h2: 'Know your customer, track their balance, give them an app',
      p: 'A card for every customer you gather on stream: account/balance, refunds and history in one place. Blacklist troublesome users; Shopper handles the rest.',
      feats: [
        ['Account & balance', 'Customer card, balance, refunds and order history.'],
        ['Blacklist', 'Flag troublesome users and keep them out automatically.'],
        ['Shopper app', 'Customers sign up, see their orders and balance, and reset their own password.'],
        ['Instant push notifications', 'New stream, announcement and payment events notify the customer instantly via Shopper.'],
        ['Announcements & feed', 'Share text + photos; customers see them in the Shopper feed and get a push.'],
        ['Custom signup form', 'Collect customers with a stream-specific, customizable form.'],
      ],
      push: ['🔔 OrderDeck · ', 'Stream started!', ' Tonight at 21:00'],
      orders: 'My orders',
      order1: ['Purple knit · 38', 'Stream #318 · ₺250', 'Paid'],
      order2: ['Shawl · cream', 'Stream #318 · ₺120', 'Pending'],
      order3: ['Shipping', 'Below threshold · ₺60', 'Pending'],
      balLabel: 'Current balance',
      balPending: 'Pending payment',
      balMonth: 'Orders this month',
      payBtn: 'Pay via WhatsApp',
      pwHint: 'You can reset your password yourself from the app.',
    },
    trust: [
      ['Local and private', 'Chat data stays on your machine. It is never sent to OrderDeck servers; it’s wiped when the app closes.', null],
      ['Backup & restore', 'Back up data, restore it, move your license to another machine. A breakdown won’t stop your work.', null],
      ['Automatic updates', 'New versions arrive from inside the app. You just focus on the stream.', null],
      ['Bulk SMS campaigns', 'Bulk campaigns to your customer list. ', 'Coming soon.'],
    ],
    pricing: {
      kicker: 'PRICING',
      h2: 'Pay once, yours for life',
      p: 'No subscription. The version you buy is yours; first year of updates included, after that entirely optional.',
      badge: 'LIFETIME LICENSE',
      price: '250,000\u00a0₺',
      priceNote: 'one-time',
      feats: ['All 4 platforms','Instant label printing','Backup sale + shipping threshold','WhatsApp payment request','Bank receipt verification','Giveaway + OBS overlay','Automatic winner label','Customer / account / balance','Shopper + push notifications','Announcements & custom form','Stream report + history → Excel','Spam & troll filter','Backup & restore','First year of updates included'],
      cta: 'Get a license',
      ctaNote: 'Single person/business license · activation via WhatsApp',
      addonKicker: 'LATER YEARS — OPTIONAL',
      addonTitle: 'Updates + support',
      addonPrice: '10,000\u00a0₺',
      addonPer: '/year',
      addonP: 'New features, API fixes for platform changes, priority e-mail support (reply within 24 hours). The first year is included free; if you skip it, your current version keeps working.',
      ctxKicker: 'WHAT IT REMOVES',
      ctxP: 'The second phone, the tabs left open, the lost order and the “who bought what” argument. One window, one feed, clean records.',
      trial: '14-day full free trial · no card required',
    },
    faqTitle: { kicker: 'FREQUENTLY ASKED', h2: 'Common questions' },
    faq: [
      ['What is OrderDeck?', 'A Windows desktop app that unifies Instagram, TikTok, Facebook and YouTube live chat, takes orders and prints labels, and runs giveaways and customer management. Built for broadcasters who sell live, auction-style.'],
      ['Which printers are supported?', 'Every thermal label printer installed on Windows works. It was tested with Argox, Zebra and TSC models during development.'],
      ['Do I need an extra account/API key for the platforms?', 'No. You don’t need to create a separate API key or developer account; you sign in with the platform accounts you want to connect and start streaming.'],
      ['Are messages stored anywhere?', 'No. All messages are kept only on your machine, up to the last 500 in memory, and wiped when the app closes. Nothing is sent to OrderDeck servers.'],
      ['How does the trial work?', 'A 14-day full free trial is active on first install. When it ends, if you don’t buy a license the app switches to read-only; your old labels are kept but you can’t open new streams.'],
      ['Does a license work on more than one machine?', 'One license is tied to one machine. You can transfer between machines from the panel without opening a support request (twice a month).'],
      ['Why a lifetime license instead of a subscription?', 'Because OrderDeck depends on external platforms, we maintain it constantly as they change. You pay once and own it; we keep up maintenance with an optional update pack. The model is fair for both sides.'],
    ] as [string, string][],
    download: {
      kicker: 'DOWNLOAD',
      h2: 'Install OrderDeck tonight',
      p: 'Self-contained installer for Windows 10 (22H2+) and 11 — no extra .NET or other runtime to install.',
      version: 'VERSION',
      size: 'SIZE',
      date: 'RELEASED',
      btn: 'Download now',
      sub: '14-day full trial · no card required',
      warnH: 'If a SmartScreen warning appears',
      warnP: 'OrderDeck is currently distributed without a code-signing certificate (coming in Q3 2026). If Windows shows a “protected your PC” warning:',
      warnSteps: ['Click the “More info” link', 'Click the “Run anyway” button'],
      afterH: 'After installation',
      afterSteps: ['The setup wizard starts automatically on first launch.', 'In 6 steps it sets up license activation, YouTube channel settings, the Chrome extension and OBS browser source URLs.', 'While the Chrome extension awaits store approval, the wizard shows the sideload steps.'],
      reqH: 'System requirements',
      req: ['Windows 10 (22H2+) or Windows 11', '64-bit processor (Intel/AMD or ARM64)', '~500 MB free disk space', 'Internet connection for license activation', 'Google Chrome (for live chat)'],
    },
    footer: {
      tagline: 'Chat, labels and giveaways in one window for Turkish live-auction sellers.',
      contact: 'Musa Sevinç · support@orderdeckapp.com',
      colProduct: 'Product',
      product: [['#ozellikler','Features'],['#fiyat','Pricing'],['#sss','FAQ'],['/en/blog/','Blog']],
      colLegal: 'Legal',
      legal: [['/en/privacy-policy/','Privacy Policy'],['/en/terms-of-service/','Terms of Service'],['/en/contact/','Contact']],
      rights: '© 2026 Musa Sevinç. All rights reserved.',
    },
    chatPool: [
      { p: 'ig', u: 'ayse34', m: 'sold 250', buy: true, price: 250, item: 'red 38' },
      { p: 'tt', u: 'mehmet_k', m: 'any XL?' },
      { p: 'fb', u: 'fatma.gul', m: 'sold red 38', buy: true, price: 180, item: 'red 38' },
      { p: 'yt', u: 'ali_eks', m: 'save one for me' },
      { p: 'ig', u: 'zey.no', m: 'joined the giveaway' },
      { p: 'tt', u: 'derya.b', m: 'how much is it' },
      { p: 'ig', u: 'selin_24', m: 'sold 320', buy: true, price: 320, item: 'purple knit' },
      { p: 'fb', u: 'hatice.k', m: 'is shipping included' },
      { p: 'yt', u: 'burak.t', m: 'sold 150', buy: true, price: 150, item: 'cream shawl' },
      { p: 'tt', u: 'esra_m', m: 'size chart?' },
      { p: 'ig', u: 'gul.han', m: 'sold 410', buy: true, price: 410, item: 'coat L' },
      { p: 'fb', u: 'yusuf99', m: 'any stock left' },
    ],
    printerSamples: [
      { plat: 'IG', user: 'ayse34', item: 'red knit · 38', price: 250, cargo: false, standby: false },
      { plat: 'TT', user: 'mehmet_k', item: 'coat · L', price: 410, cargo: true, standby: false },
      { plat: 'FB', user: 'selin_24', item: 'purple dress · M', price: 180, cargo: false, standby: true },
      { plat: 'YT', user: 'gul.han', item: 'shawl · cream', price: 120, cargo: true, standby: false },
    ],
  },
} as const;

export type LandingCopy = (typeof landingCopy)['tr'];
